(() => {
  const titles={dashboard:["Visão geral","Dashboard"],products:["Catálogo","Produtos"],sales:["Operações","Vendas"],deliveries:["Logística","Entregas"],finance:["Resultados","Financeiro"],reports:["Análise","Relatórios"],history:["Atividade","Histórico"],settings:["Sistema","Configurações"]};
  const routes={dashboard:Dashboard.render,products:Products.render,sales:Sales.render,deliveries:Deliveries.render,finance:Finance.render,reports:Reports.render,settings:SettingsPage.render,history:historyPage};
  const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  function navigate(route){route=routes[route]?route:"dashboard";document.querySelectorAll(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.route===route));document.getElementById("page-kicker").textContent=titles[route][0];document.getElementById("page-title").textContent=titles[route][1];routes[route]();history.replaceState(null,"","#"+route);document.getElementById("sidebar").classList.remove("open");document.getElementById("mobile-overlay").classList.remove("show");}
  function historyPage(){const h=Store.get("history").slice().sort((a,b)=>b.date.localeCompare(a.date));document.getElementById("content").innerHTML=`<div class="page-head"><div><div class="eyebrow">ATIVIDADE</div><h1>Histórico</h1><p>Registro cronológico das principais movimentações do sistema.</p></div></div><div class="panel"><div class="toolbar"><input id="history-search" class="small-search" placeholder="Pesquisar atividade..."><select id="history-type"><option value="">Todos os tipos</option><option>compra</option><option>venda</option><option>entrega</option><option>alteração</option><option>exclusão</option></select></div><div id="history-list"></div></div>`;const paint=()=>{const q=document.getElementById("history-search").value.toLowerCase(),t=document.getElementById("history-type").value,a=h.filter(x=>(!t||x.type===t)&&x.description.toLowerCase().includes(q));document.getElementById("history-list").innerHTML=a.length?a.map(x=>`<div class="history-row"><span class="history-icon">${x.type==="venda"?"↗":x.type==="entrega"?"⌁":"•"}</span><div><strong>${esc(x.description)}</strong><small>${new Date(x.date).toLocaleString("pt-BR")}</small></div><span class="badge neutral">${esc(x.type)}</span></div>`).join(""):`<div class="empty-state"><h3>Nenhuma atividade</h3></div>`};document.getElementById("history-search").oninput=paint;document.getElementById("history-type").onchange=paint;paint();}
  function modal(html){document.getElementById("modal").innerHTML=html;document.getElementById("modal-backdrop").classList.remove("hidden");document.querySelectorAll("[data-close]").forEach(b=>b.onclick=closeModal)}
  function closeModal(){document.getElementById("modal-backdrop").classList.add("hidden");document.getElementById("modal").innerHTML=""}
  function toast(message,type="info"){const t=document.createElement("div");t.className=`toast ${type}`;t.innerHTML=`<span>${type==="success"?"✓":type==="error"?"!":"i"}</span>${esc(message)}`;document.getElementById("toast-container").appendChild(t);setTimeout(()=>t.classList.add("show"),10);setTimeout(()=>{t.classList.remove("show");setTimeout(()=>t.remove(),250)},3200)}
  function applyTheme(){document.documentElement.dataset.theme=Store.get("settings").theme||"light";document.getElementById("theme-toggle").textContent=document.documentElement.dataset.theme==="dark"?"☀":"☾"}
  function exportBackup(){const blob=new Blob([Store.exportJSON()],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`backup-estoque-thiago-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast("Backup exportado com sucesso.","success")}
  window.App={navigate,modal,closeModal,toast,applyTheme,exportBackup};
  window.escapeHtml=esc;
  document.addEventListener("click",e=>{const nav=e.target.closest("[data-route]");if(nav)navigate(nav.dataset.route);const action=e.target.closest("[data-action]");if(action&&action.dataset.action==="export-backup")exportBackup()});
  document.getElementById("mobile-menu").onclick=()=>{document.getElementById("sidebar").classList.add("open");document.getElementById("mobile-overlay").classList.add("show")};document.getElementById("mobile-overlay").onclick=()=>{document.getElementById("sidebar").classList.remove("open");document.getElementById("mobile-overlay").classList.remove("show")};
  document.getElementById("modal-backdrop").onclick=e=>{if(e.target.id==="modal-backdrop")closeModal()};
  document.getElementById("theme-toggle").onclick=()=>{Store.update("settings",s=>({...s,theme:s.theme==="dark"?"light":"dark"}));applyTheme()};
  document.getElementById("global-search").oninput=e=>{const q=e.target.value.trim().toLowerCase(),box=document.getElementById("search-results");if(!q){box.classList.add("hidden");return}const p=Store.get("products").filter(x=>`${x.name} ${x.brand} ${x.model} ${x.sku} ${x.category}`.toLowerCase().includes(q)).slice(0,7);box.innerHTML=p.length?p.map(x=>`<button data-product-search="${x.id}"><b>${esc(x.name)}</b><span>${esc(x.sku||"Sem SKU")} · estoque ${x.stock}</span></button>`).join(""):`<div class="search-empty">Nenhum produto encontrado.</div>`;box.classList.remove("hidden")};
  document.addEventListener("click",e=>{const b=e.target.closest("[data-product-search]");if(b){document.getElementById("global-search").value="";document.getElementById("search-results").classList.add("hidden");navigate("products");setTimeout(()=>Products.openProduct(b.dataset.productSearch),80)}});
  window.addEventListener("popstate",()=>navigate(location.hash.slice(1)));applyTheme();navigate(location.hash.slice(1)||"dashboard");
})();