window.Dashboard = (() => {
  const n=v=>Number(v)||0,money=v=>(n(v)).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
  function periodStart(filter){const now=new Date(),d=new Date(now);if(filter==="today"){d.setHours(0,0,0,0);return d;} if(filter==="7")d.setDate(d.getDate()-6);else if(filter==="30")d.setDate(d.getDate()-29);else if(filter==="prev"){d.setMonth(d.getMonth()-1);d.setDate(1);return d;}else if(filter==="month")d.setDate(1);else d.setHours(0,0,0,0);return d;}
  function render(){
    const sales=Store.get("sales"), products=Store.get("products"), deliveries=Store.get("deliveries"), gas=deliveries.reduce((s,d)=>s+n(d.gasCost),0), revenue=sales.reduce((s,x)=>s+n(x.total),0), productCost=sales.reduce((s,x)=>s+n(x.productCost),0), gross=sales.reduce((s,x)=>s+n(x.grossProfit),0), net=sales.reduce((s,x)=>s+n(x.netProfit),0), stockCost=products.reduce((s,p)=>s+n(p.stock)*n(p.costUnit),0),stockSale=products.reduce((s,p)=>s+n(p.stock)*n(p.salePrice),0);
    const low=products.filter(p=>n(p.stock)>0&&n(p.stock)<=n(Store.get("settings").minStock)), out=products.filter(p=>n(p.stock)<=0);
    document.getElementById("content").innerHTML=`<div class="page-head"><div><div class="eyebrow">VISÃO GERAL</div><h1>Dashboard</h1><p>Tenha uma visão rápida do estoque, vendas e resultado do seu negócio.</p></div><div class="head-actions"><select id="dash-period"><option value="today">Hoje</option><option value="7">Últimos 7 dias</option><option value="30">Últimos 30 dias</option><option value="month" selected>Este mês</option><option value="prev">Mês anterior</option></select><button class="btn primary" id="dash-sale">＋ Registrar venda</button></div></div>
    <div class="kpi-grid"><div class="kpi-card accent"><span>Valor investido no estoque</span><strong>${money(stockCost)}</strong><small>Capital atualmente parado</small></div><div class="kpi-card"><span>Valor de venda do estoque</span><strong>${money(stockSale)}</strong><small>Receita potencial</small></div><div class="kpi-card"><span>Lucro potencial</span><strong class="positive">${money(stockSale-stockCost)}</strong><small>Se todo estoque for vendido</small></div><div class="kpi-card"><span>Total recebido</span><strong>${money(revenue)}</strong><small>${sales.length} venda(s) registrada(s)</small></div><div class="kpi-card"><span>Custo dos produtos vendidos</span><strong>${money(productCost)}</strong></div><div class="kpi-card"><span>Gastos com gasolina</span><strong>${money(gas)}</strong></div><div class="kpi-card"><span>Lucro bruto</span><strong class="positive">${money(gross)}</strong></div><div class="kpi-card"><span>Lucro líquido / real</span><strong class="${net>=0?"positive":"negative"}">${money(net)}</strong></div></div>
    <div class="dashboard-grid"><div class="panel chart-panel"><div class="panel-head"><div><h2>Vendas & lucro</h2><span>Movimentação registrada</span></div></div><div id="sales-chart" class="chart"></div></div>
    <div class="panel"><div class="panel-head"><div><h2>Saúde do estoque</h2><span>Visão atual</span></div></div><div class="stock-health"><div class="ring"><div><b>${products.reduce((s,p)=>s+n(p.stock),0)}</b><small>unidades</small></div></div><div class="health-list"><span><i class="dot normal"></i>Normal <b>${products.length-low.length-out.length}</b></span><span><i class="dot warn"></i>Estoque baixo <b>${low.length}</b></span><span><i class="dot danger"></i>Esgotado <b>${out.length}</b></span></div></div></div></div>
    <div class="dashboard-grid"><div class="panel"><div class="panel-head"><div><h2>Produtos mais vendidos</h2><span>Por quantidade</span></div></div><div id="top-products"></div></div><div class="panel"><div class="panel-head"><div><h2>Alertas</h2><span>Ações que merecem atenção</span></div></div><div class="alerts">${alerts(low,out,net,gas)}</div></div></div>`;
    document.getElementById("dash-period").onchange=e=>drawChart(e.target.value);document.getElementById("dash-sale").onclick=Sales.openSale;drawChart("month");topProducts();
  }
  function drawChart(filter){const root=document.getElementById("sales-chart"),start=periodStart(filter),sales=Store.get("sales").filter(s=>new Date(s.date)>=start);const days=Math.max(1,Math.ceil((new Date()-start)/86400000)+1), vals=Array.from({length:Math.min(days,14)},(_,i)=>({rev:0,profit:0,label:""}));sales.forEach(s=>{const idx=Math.min(vals.length-1,Math.max(0,Math.floor((new Date(s.date)-start)/86400000)));vals[idx].rev+=n(s.total);vals[idx].profit+=n(s.netProfit);});const max=Math.max(1,...vals.map(x=>x.rev));root.innerHTML=`<div class="bar-chart">${vals.map(v=>`<div class="bar-col" title="${money(v.rev)}"><div class="bar" style="height:${Math.max(3,v.rev/max*100)}%"></div><small>${money(v.rev).replace("R$","").trim()}</small></div>`).join("")}</div><div class="chart-legend"><span><i class="legend-dot"></i> Receita</span><span><i class="legend-dot second"></i> Resultado real</span></div>`}
  function topProducts(){const map={};Store.get("sales").forEach(s=>s.items.forEach(i=>map[i.name]=(map[i.name]||0)+n(i.qty)));const arr=Object.entries(map).sort((a,b)=>b[1]-a[1]).slice(0,5);document.getElementById("top-products").innerHTML=arr.length?arr.map(([name,q],i)=>`<div class="rank-row"><span class="rank">${i+1}</span><div><strong>${name}</strong><div class="rank-track"><i style="width:${q/(arr[0][1]||1)*100}%"></i></div></div><b>${q} un.</b></div>`).join(""):`<div class="empty-inline">As vendas aparecerão aqui.</div>`}
  function alerts(low,out,net,gas){let a=[];out.slice(0,3).forEach(p=>a.push(`<div class="alert danger"><b>${p.name}</b><span>está esgotado.</span></div>`));low.slice(0,3).forEach(p=>a.push(`<div class="alert warning"><b>${p.name}</b><span>está com estoque baixo (${p.stock}).</span></div>`));if(net>0)a.push(`<div class="alert success"><b>${money(net)}</b><span>de lucro real acumulado.</span></div>`);if(gas>0)a.push(`<div class="alert info"><b>${money(gas)}</b><span>em gasolina nas entregas.</span></div>`);return a.length?a.join(""):`<div class="empty-inline">Tudo certo por aqui.</div>`}
  return {render};
})();