window.Deliveries = (() => {
  const money=v=>(Number(v)||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"}), n=v=>Number(v)||0;
  const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  function gas(km){const s=Store.get("settings"), liters=n(km)/Math.max(.01,n(s.motorcycle.consumption));return {liters,cost:liters*n(s.motorcycle.gasPrice)};}
  function render(){
    const ds=Store.get("deliveries").slice().sort((a,b)=>b.date.localeCompare(a.date)), totalKm=ds.reduce((s,d)=>s+n(d.totalKm),0), gasTotal=ds.reduce((s,d)=>s+n(d.gasCost),0);
    document.getElementById("content").innerHTML=`<div class="page-head"><div><div class="eyebrow">LOGÍSTICA</div><h1>Entregas</h1><p>Controle quilômetros, combustível e custo real de cada deslocamento.</p></div><button class="btn primary" id="new-delivery">＋ Nova entrega</button></div>
    <div class="kpi-grid compact"><div class="kpi-card"><span>Entregas</span><strong>${ds.length}</strong></div><div class="kpi-card"><span>Quilômetros</span><strong>${totalKm.toFixed(1)} km</strong></div><div class="kpi-card"><span>Gasolina estimada</span><strong>${money(gasTotal)}</strong></div><div class="kpi-card"><span>Consumo configurado</span><strong>${n(Store.get("settings").motorcycle.consumption).toFixed(1)} km/L</strong></div></div>
    <div class="panel"><div class="panel-head"><div><h2>Histórico de entregas</h2><span>Custos calculados automaticamente</span></div></div><div class="table-wrap"><table><thead><tr><th>Data</th><th>Saída → Cliente → Próximo</th><th>KM</th><th>Combustível</th><th>Custo</th><th>Venda</th></tr></thead><tbody>${ds.length?ds.map(d=>`<tr><td>${new Date(d.date).toLocaleDateString("pt-BR")}</td><td><strong>${esc(d.start||"—")} → ${esc(d.customerLocation||"—")} → ${esc(d.nextDestination||"—")}</strong></td><td>${n(d.totalKm).toFixed(1)} km</td><td>${n(d.liters).toFixed(2)} L</td><td>${money(d.gasCost+n(d.otherCosts))}</td><td>${d.saleId?"Vinculada":"Avulsa"}</td></tr>`).join(""):`<tr><td colspan="6"><div class="empty-inline">Nenhuma entrega registrada.</div></td></tr>`}</tbody></table></div></div>`;
    document.getElementById("new-delivery").onclick=()=>openDelivery();
  }
  function fields(target, prefix="delivery"){
    target.innerHTML=`<div class="form-grid"><label>Local de saída<input name="${prefix}-start" placeholder="Ex.: Minha casa"></label><label>Local do cliente<input name="${prefix}-client" placeholder="Ex.: Casa do cliente"></label><label>Destino após a entrega<input name="${prefix}-next" placeholder="Ex.: Trabalho"></label><label>KM saída → cliente<input name="${prefix}-km1" type="number" min="0" step="0.1" value="0"></label><label>KM cliente → próximo destino<input name="${prefix}-km2" type="number" min="0" step="0.1" value="0"></label></div><div class="delivery-calc" id="${prefix}-calc"></div>`;
    const update=()=>{const km1=n(target.querySelector(`[name="${prefix}-km1"]`).value),km2=n(target.querySelector(`[name="${prefix}-km2"]`).value),g=gas(km1+km2);target.querySelector(`#${prefix}-calc`).innerHTML=`<span>Distância total <b>${(km1+km2).toFixed(1)} km</b></span><span>Consumo <b>${g.liters.toFixed(2)} L</b></span><span>Custo de gasolina <b>${money(g.cost)}</b></span>`};target.oninput=update;update();
  }
  function mountSaleFields(target){ fields(target,"delivery"); }
  function fromSaleForm(fd){
    const root=document.getElementById("delivery-fields"), km1=n(root.querySelector('[name="delivery-km1"]')?.value),km2=n(root.querySelector('[name="delivery-km2"]')?.value),g=gas(km1+km2);
    const d={id:Store.uid("del"),date:new Date().toISOString(),start:root.querySelector('[name="delivery-start"]')?.value||"",customerLocation:root.querySelector('[name="delivery-client"]')?.value||"",nextDestination:root.querySelector('[name="delivery-next"]')?.value||"",km1,km2,totalKm:km1+km2,liters:g.liters,gasCost:g.cost,otherCosts:0,saleId:null};
    Store.add("deliveries",d);return d;
  }
  function openDelivery(){
    App.modal(`<div class="modal-head"><div><div class="eyebrow">LOGÍSTICA</div><h2>Nova entrega</h2></div><button class="modal-close" data-close>×</button></div><form id="delivery-form" class="form"><div id="delivery-form-fields"></div><label>Outros custos da entrega<input name="otherCosts" type="number" min="0" step="0.01" value="0"></label><label>Observações<textarea name="notes"></textarea></label><div class="modal-actions"><button type="button" class="btn ghost" data-close>Cancelar</button><button class="btn primary">Salvar entrega</button></div></form>`);
    const target=document.getElementById("delivery-form-fields");fields(target,"d");document.getElementById("delivery-form").onsubmit=e=>{e.preventDefault();const root=e.target,km1=n(root.querySelector('[name="d-km1"]').value),km2=n(root.querySelector('[name="d-km2"]').value),g=gas(km1+km2),d={id:Store.uid("del"),date:new Date().toISOString(),start:root.querySelector('[name="d-start"]').value,customerLocation:root.querySelector('[name="d-client"]').value,nextDestination:root.querySelector('[name="d-next"]').value,km1,km2,totalKm:km1+km2,liters:g.liters,gasCost:g.cost,otherCosts:n(root.querySelector('[name="otherCosts"]').value),notes:root.querySelector('[name="notes"]').value,saleId:null};Store.add("deliveries",d);Store.add("history",{id:Store.uid("hist"),type:"entrega",description:`Entrega de ${d.totalKm.toFixed(1)} km`,date:d.date,deliveryId:d.id});App.closeModal();App.toast("Entrega registrada.","success");render();};
  }
  return {render,openDelivery,mountSaleFields,fromSaleForm,gas};
})();