window.Reports = (() => {
  const n=v=>Number(v)||0,money=v=>n(v).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
  const csv=(rows)=>rows.map(r=>r.map(v=>`"${String(v??"").replace(/"/g,'""')}"`).join(";")).join("\n");
  function download(name,content,type="text/csv"){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
  function render(){document.getElementById("content").innerHTML=`<div class="page-head"><div><div class="eyebrow">ANÁLISE</div><h1>Relatórios</h1><p>Exporte dados e gere visões para acompanhar o negócio.</p></div></div><div class="report-grid">${[
    ["Vendas","Histórico completo de vendas","sales"],["Estoque","Produtos e quantidades atuais","products"],["Entregas","Quilometragem e gasolina","deliveries"],["Produtos parados","Produtos sem nenhuma venda","stalled"],["Produtos esgotados","Produtos sem unidades disponíveis","out"],["Lucros","Resumo de receita e resultado","profits"]
  ].map(x=>`<article class="report-card"><div class="report-icon">▤</div><h3>${x[0]}</h3><p>${x[1]}</p><button class="btn ghost" data-report="${x[2]}">Exportar CSV</button></article>`).join("")}</div><div class="panel report-actions"><div><h2>Impressão / PDF</h2><p>Use a impressão do navegador para salvar qualquer relatório como PDF.</p></div><button class="btn primary" onclick="window.print()">Imprimir página</button><button class="btn ghost" id="json-export">Exportar JSON</button></div>`;
    document.querySelectorAll("[data-report]").forEach(b=>b.onclick=()=>exportReport(b.dataset.report));document.getElementById("json-export").onclick=()=>{download("estoque-thiago-backup.json",Store.exportJSON(),"application/json")};
  }
  function exportReport(type){let rows=[];if(type==="sales"){rows=[["Data","Cliente","Produtos","Recebido","Custo","Lucro bruto","Gasolina","Outros","Lucro real"],...Store.get("sales").map(s=>[new Date(s.date).toLocaleString("pt-BR"),s.customer,s.items.map(i=>`${i.name} x${i.qty}`).join(", "),money(s.total),money(s.productCost),money(s.grossProfit),money(s.gasCost),money(s.otherCosts),money(s.netProfit)])]}else if(type==="products"){rows=[["Produto","SKU","Estoque","Custo/un.","Venda","Lucro/un.","Margem"],...Store.get("products").map(p=>[p.name,p.sku,p.stock,money(p.costUnit),money(p.salePrice),money(p.salePrice-p.costUnit),p.salePrice?(p.salePrice-p.costUnit)/p.salePrice*100+"%":"0%"])]}else if(type==="deliveries"){rows=[["Data","Saída","Cliente","Próximo destino","KM","Litros","Gasolina","Outros"],...Store.get("deliveries").map(d=>[new Date(d.date).toLocaleString("pt-BR"),d.start,d.customerLocation,d.nextDestination,d.totalKm,d.liters,money(d.gasCost),money(d.otherCosts)])]}else if(type==="stalled"){const sold=new Set(Store.get("sales").flatMap(s=>s.items.map(i=>i.productId)));rows=[["Produto","Estoque"],...Store.get("products").filter(p=>!sold.has(p.id)).map(p=>[p.name,p.stock])]}else if(type==="out"){rows=[["Produto","SKU"],...Store.get("products").filter(p=>n(p.stock)<=0).map(p=>[p.name,p.sku])]}else {const s=Store.get("sales");rows=[["Receita","Custo produtos","Gasolina","Outros custos","Lucro real"],[money(s.reduce((a,x)=>a+n(x.total),0)),money(s.reduce((a,x)=>a+n(x.productCost),0)),money(s.reduce((a,x)=>a+n(x.gasCost),0)),money(s.reduce((a,x)=>a+n(x.otherCosts),0)),money(s.reduce((a,x)=>a+n(x.netProfit),0))]]}download(`relatorio-${type}.csv`,csv(rows));App.toast("Relatório exportado.","success")}
  return {render};
})();