window.SettingsPage = (() => {
  function render(){const s=Store.get("settings");document.getElementById("content").innerHTML=`<div class="page-head"><div><div class="eyebrow">SISTEMA</div><h1>Configurações</h1><p>Personalize custos de entrega e comportamento do sistema.</p></div></div>
  <form id="settings-form" class="settings-grid"><div class="panel"><div class="panel-head"><div><h2>Dados da moto</h2><span>Usados para calcular gasolina</span></div></div><div class="form"><label>Modelo<input name="model" value="${s.motorcycle.model||""}" placeholder="Ex.: Honda CG 160"></label><div class="form-grid"><label>Consumo médio (km/L)<input name="consumption" type="number" min="1" step="0.1" value="${s.motorcycle.consumption}"></label><label>Preço da gasolina<input name="gasPrice" type="number" min="0" step="0.01" value="${s.motorcycle.gasPrice}"></label></div></div></div>
  <div class="panel"><div class="panel-head"><div><h2>Preferências</h2><span>Comportamento geral</span></div></div><div class="form"><label>Estoque mínimo padrão<input name="minStock" type="number" min="0" step="1" value="${s.minStock}"></label><label>Tema<select name="theme"><option value="light" ${s.theme==="light"?"selected":""}>Claro</option><option value="dark" ${s.theme==="dark"?"selected":""}>Escuro</option></select></label></div></div>
  <div class="panel full-panel"><div class="panel-head"><div><h2>Backup e dados</h2><span>Seus dados ficam neste navegador</span></div></div><div class="backup-actions"><button type="button" class="btn primary" data-action="export-backup">↓ Exportar backup</button><label class="btn ghost file-btn">↑ Importar backup<input id="import-backup" type="file" accept=".json,application/json" hidden></label><button type="button" class="btn danger" id="clear-data">Limpar todos os dados</button></div><p class="muted">Recomendação: exporte um backup periodicamente. O JSON contém produtos, vendas, entregas, custos, configurações e histórico.</p></div><div class="save-settings"><button class="btn primary">Salvar configurações</button></div></form>`;
  document.getElementById("settings-form").onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target);Store.update("settings",s=>({...s,minStock:Number(fd.get("minStock"))||0,motorcycle:{model:fd.get("model"),consumption:Number(fd.get("consumption"))||30,gasPrice:Number(fd.get("gasPrice"))||0},theme:fd.get("theme")}));App.applyTheme();App.toast("Configurações salvas.","success");render()};
  document.getElementById("clear-data").onclick=()=>{if(confirm("ATENÇÃO: isso apagará produtos, vendas, entregas e histórico deste navegador. Deseja continuar?")){Store.reset();App.toast("Todos os dados foram apagados.","success");render()}};
  document.getElementById("import-backup").onchange=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{Store.importJSON(r.result);App.applyTheme();App.toast("Backup restaurado com sucesso.","success");render()}catch(err){App.toast("Arquivo de backup inválido.","error")}};r.readAsText(f)};
  }
  return {render};
})();